# docker-compose.yml

services:
  web:
    build: .
    container_name: ${NAME}
    command: >
      sh -c "gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2 --worker-class gthread --timeout 660 --log-level info --access-logfile - --error-logfile -"
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - /app/theme/static_src/node_modules
      - /app/theme/static
      - static_volume:/app/staticfiles
      - db_volume:/app/db
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true
    restart: unless-stopped

    
volumes:
  static_volume:
  db_volume: