# Generated by Django 5.2.3 on 2026-06-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PauzeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Wina Pauze', max_length=200)),
                ('subtitle', models.CharField(default='Subtitle', max_length=255)),
                ('content', models.TextField(default='')),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
